input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  # Itt alakítjuk át a koordinátákat olyan formátumba, amit az Elastic szeret
  mutate {
    add_field => { "[location][lat]" => "%{latitude}" }
    add_field => { "[location][lon]" => "%{longitude}" }
  }
  mutate {
    convert => {
      "[location][lat]" => "float"
      "[location][lon]" => "float"
      "speed" => "float"
      "fuel" => "float"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bus-telemetry-%{+YYYY.MM.dd}"
  }
  # Ez csak azért kell, hogy a konzolon is lásd, ha jön adat
  stdout { codec => rubydebug }
}
