input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  # Koordináták átalakítása az Elascicsearch-nek
  mutate {
    add_field => { "[location][lat]" => "%{latitude}" }
    add_field => { "[location][lon]" => "%{longitude}" }
  }
  mutate {
    convert => {
      "[location][lat]" => "float"
      "[location][lon]" => "float"
      "speed" => "float"
      "fuel" => "float"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bus-telemetry-%{+YYYY.MM.dd}"
  }
  # A konzolos adatmegjelenítéshez
  stdout { codec => rubydebug }
}


